version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    env_file:
      - .env.local
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/mm-server
    command: air
