version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    depends_on:
      - "db"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - LINE_LOGIN_CHANNEL_ID=${LINE_LOGIN_CHANNEL_ID}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/mm-server
    command: air
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${DB_TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./build/db/logs:/var/log/mysql
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./build/db/initdb.d:/docker-entrypoint-initdb.d
