name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install wire
        run: go get github.com/google/wire/cmd/wire

      - name: Run wire
        run: wire
        working-directory: ./cmd/http/di

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet --no-promote --version v1
